import type { Effect, EventFamily } from '../../types';
import { beat, ch, skip } from './factory';

/** 开窗通风：此后不再掷 CO，清掉中毒，会被看见 */
const VENT_OPEN: Effect = {
  setFlags: ['flag:coVenting'],
  removeCond: ['coPoisoning'],
  world: { exposure: 10 },
  tone: 'good',
};

/** 室内温度伴生：寒潮、低温症、估错了的一夜 */
export const COLD_EVENTS: EventFamily[] = [
  beat({
    id: 'env_first_freeze',
    kind: 'weather',
    intensity: 3,
    phase: ['survival'],
    weight: 0,
    once: true,
    require: { all: ['indoor:freeze'] },
    choices: [
      ch(
        'closet',
        { res: { fuel: 3 }, stats: { stamina: -8 }, tone: 'good' },
      ),
      ch(
        'battery',
        { wear: { batteryCharge: 2 }, stats: { stamina: -6 }, tone: 'good' },
      ),
      ch('leave', { stats: { sanity: -2 }, tone: 'neutral' }),
    ],
  }),
  beat({
    id: 'env_cold_streak',
    kind: 'weather',
    intensity: 3,
    phase: ['survival'],
    weight: 7,
    minThreat: 3,
    maxThreat: 6,
    cooldown: 12,
    require: { all: ['indoor:freeze', 'streak:belowSurvival>=3'] },
    choices: [
      ch(
        'chair',
        {
          res: { materials: -2 },
          indoor: 4,
          stats: { stamina: -10, sanity: -3 },
          setFlags: ['flag:burnedChair'],
          tone: 'neutral',
        },
        { requires: { res: { materials: 2 } } },
      ),
      ch(
        'can',
        { res: { fuel: 2.5 }, stats: { stamina: -12 }, tone: 'good' },
      ),
      skip({ stats: { hp: -3, stamina: -4, sanity: -3 } }),
    ],
  }),
  beat({
    id: 'env_hypo_severe',
    kind: 'medical',
    intensity: 4,
    phase: ['survival'],
    weight: 0,
    cooldown: 6,
    require: { all: ['cond:hypothermiaSevere'] },
    choices: [
      ch(
        'dump_fuel',
        {
          res: { fuel: -6 },
          indoor: 6,
          stats: { stamina: -8 },
          tone: 'good',
        },
        { requires: { res: { fuel: 6 } } },
      ),
      ch(
        'break_table',
        {
          res: { materials: -3 },
          indoor: 3,
          stats: { stamina: -14, sanity: -4 },
          setFlags: ['flag:burnedChair'],
          tone: 'neutral',
        },
        { requires: { res: { materials: 3 } } },
      ),
      ch('huddle', { stats: { hp: -10, stamina: -8, sanity: -4 }, indoor: 1, tone: 'neutral' }),
    ],
  }),
  beat({
    id: 'env_warmth_return',
    kind: 'story',
    intensity: 2,
    phase: ['survival'],
    weight: 0,
    cooldown: 10,
    require: { all: ['indoor:warm', 'flag:wasCold'] },
    choices: [
      ch('sit', { stats: { sanity: 6, stamina: 4 }, clearFlags: ['flag:wasCold'], tone: 'good' }),
      ch(
        'share',
        {
          res: { water: -2 },
          stats: { humanity: 4, sanity: 3 },
          world: { neighborhood: 6, exposure: 4 },
          clearFlags: ['flag:wasCold'],
          tone: 'good',
        },
        { requires: { res: { water: 2 } } },
      ),
      ch('keep', { stats: { sanity: 2 }, clearFlags: ['flag:wasCold'], tone: 'neutral' }),
    ],
  }),
  beat({
    id: 'env_first_chill',
    kind: 'weather',
    intensity: 2,
    phase: ['survival'],
    weight: 0,
    once: true,
    require: { all: ['indoor:chill'] },
    choices: [
      ch('coat', { stats: { stamina: -4, sanity: 2 }, setFlags: ['flag:layeredClothes'], tone: 'good' }),
      ch('cell', { wear: { batteryCharge: 1 }, stats: { stamina: -5 }, tone: 'good' }),
      skip({ stats: { sanity: -1 } }),
    ],
  }),
  beat({
    id: 'env_heater_fault',
    kind: 'weather',
    intensity: 2,
    phase: ['survival'],
    weight: 7,
    minThreat: 3,
    maxThreat: 6,
    cooldown: 14,
    require: { all: ['heat:electric'] },
    choices: [
      ch(
        'fix',
        { res: { parts: -1 }, wear: { batteryCharge: 1.5 }, stats: { stamina: -8 }, tone: 'good' },
        { requires: { res: { parts: 1 } } },
      ),
      ch('switch_fuel', { stats: { stamina: -4 }, heatMode: 'fuel', tone: 'neutral' }),
      skip({ stats: { sanity: -2 } }),
    ],
  }),
  beat({
    id: 'env_shared_blanket',
    kind: 'social',
    intensity: 2,
    phase: ['survival'],
    weight: 7,
    minThreat: 4,
    maxThreat: 6,
    cooldown: 12,
    require: { any: ['crew:some', 'crew:full'] },
    forbid: { all: ['indoor:warm'] },
    choices: [
      ch(
        'give',
        { survivor: { morale: 8 }, stats: { stamina: -6, sanity: 1 }, tone: 'good' },
      ),
      ch('keep_blanket', { survivor: { morale: -6 }, stats: { sanity: -2 }, setFlags: ['flag:layeredClothes'], tone: 'neutral' }),
      skip({ survivor: { morale: -2 } }),
    ],
  }),
  beat({
    id: 'env_door_left',
    kind: 'weather',
    intensity: 2,
    phase: ['survival'],
    weight: 7,
    cooldown: 10,
    choices: [
      ch('shut', { stats: { stamina: -6 }, indoor: -1, tone: 'neutral' }),
      ch('ignore', { indoor: -5, stats: { sanity: -3 }, tone: 'bad' }),
      ch('towel', { res: { materials: -1 }, indoor: -1, stats: { stamina: -4 }, tone: 'good' }, { requires: { res: { materials: 1 } } }),
    ],
  }),
  beat({
    id: 'env_ice_bucket',
    kind: 'weather',
    intensity: 2,
    phase: ['survival'],
    weight: 7,
    minThreat: 3,
    maxThreat: 6,
    cooldown: 12,
    require: { all: ['indoor:temperature<0'] },
    choices: [
      ch('thaw', { res: { fuel: -1.2 }, stats: { stamina: -6 }, tone: 'good' }, { requires: { res: { fuel: 1.2 } } }),
      ch('chip', { res: { water: -4 }, stats: { stamina: -10, sanity: -2 }, tone: 'bad' }),
      skip({ res: { water: -2 }, stats: { stamina: -3 } }),
    ],
  }),
  // 与 surv_beat_count_stock 题材重复，注释保留（2026-09 阶段化整理）
  /*
  beat({
    id: 'env_cold_ledger',
    kind: 'opportunity',
    intensity: 1,
    phase: ['survival'],
    weight: 6,
    cooldown: 16,
    require: { all: ['indoor:warm', 'flag:wasCold'] },
    choices: [
      ch('fuel_can', { res: { fuel: 2 }, stats: { stamina: -5 }, tone: 'good' }),
      ch('screws', { res: { parts: 2 }, stats: { stamina: -5 }, tone: 'good' }),
      ch('letter', { stats: { sanity: 4, stamina: -2 }, tone: 'neutral' }),
    ],
  }),
  */
  beat({
    id: 'env_woke_cold',
    kind: 'weather',
    intensity: 3,
    phase: ['survival'],
    weight: 0,
    cooldown: 8,
    require: { all: ['indoor:missed'] },
    choices: [
      ch(
        'stoke',
        { res: { fuel: -2 }, indoor: 4, stats: { stamina: -8 }, tone: 'good' },
        { requires: { res: { fuel: 2 } } },
      ),
      ch('stomp', { stats: { stamina: -10, sanity: -2 }, tone: 'neutral' }),
      ch('layers', { stats: { stamina: -4 }, setFlags: ['flag:layeredClothes'], tone: 'neutral' }),
    ],
  }),
  beat({
    id: 'env_morning_weak',
    kind: 'medical',
    intensity: 2,
    phase: ['survival'],
    weight: 8,
    cooldown: 10,
    require: { all: ['indoor:missed'] },
    forbid: { all: ['cond:hypothermiaSevere'] },
    choices: [
      ch('lie', { stats: { stamina: 12, sanity: 2 }, tone: 'good' }),
      ch('go_out', { stats: { stamina: -10 }, res: { fuel: 1.5 }, world: { exposure: 3 }, tone: 'neutral' }),
      ch('tea', { res: { water: -2 }, stats: { sanity: 4, stamina: 2 }, tone: 'good' }, { requires: { res: { water: 2 } } }),
    ],
  }),
  beat({
    id: 'env_co_alarm',
    kind: 'medical',
    intensity: 2,
    phase: ['survival'],
    weight: 0,
    once: true,
    require: { all: ['flag:coAlarm'] },
    choices: [
      ch('ok', { setFlags: ['flag:coVenting'], removeCond: ['coPoisoning'], tone: 'good' }),
    ],
  }),
  beat({
    id: 'env_co_vent',
    kind: 'medical',
    intensity: 3,
    phase: ['survival'],
    weight: 0,
    once: true,
    require: { none: ['flag:coAlarm'] },
    choices: [
      ch('open', { ...VENT_OPEN }),
      ch('keep', { setFlags: ['flag:coWarned'], tone: 'grim' }),
    ],
  }),
  beat({
    id: 'env_co_drowning',
    kind: 'medical',
    intensity: 4,
    phase: ['survival'],
    weight: 0,
    once: true,
    require: { all: ['flag:coWarned'] },
    choices: [
      ch('open', { ...VENT_OPEN }),
      ch('sleep', { stats: { hp: -999 }, tone: 'grim' }),
    ],
  }),
];
