import type { EventFamily } from '../../types';
// import type { EventVariant } from '../../types'; // 随事件一并注释（2026-09 阶段化整理）
// import { skip } from './factory'; // 随事件一并注释（2026-09 阶段化整理）

/**
 * 切片回响旗标簇：prep/切片事件的抉择旗标 → 心理回响主题。
 * 消费事件 hook_echo_sliceflags 已注释保留（与 hook_echo_oldflags 同构）；
 * 旗标数据保留导出，供 lint 的「只写不读」检查认账，未来重启回响事件时直接复用。
 */
export const ECHO_CLUSTERS = {
  water: [
    'flag:gaveWaterOnce',
    'flag:liedNoWater',
    'flag:lentRope',
    'flag:bucketToilet',
    'flag:sealedToilet',
    'flag:caughtDrip',
    'flag:filterReplaced',
    'flag:isolatedWater',
    'flag:tankKey',
    'flag:tankAsked',
  ],
  door: [
    'flag:bracedDoor',
    'flag:elevatorWarned',
    'flag:stairLit',
    'flag:stairMarked',
    'flag:windowRetaped',
    'flag:curtainsDrawn',
    'flag:shoesOutside',
    'flag:mappedClicks',
    'flag:drilledOnce',
  ],
  radio: [
    'flag:metRadioNeighbor',
    'flag:radioClip',
    'flag:copiedCoords',
    'flag:radioReplied',
    'flag:ignoredCoords',
    'flag:twoNorthStories',
    'flag:scannedBands',
  ],
  neighbor: [
    'flag:refusedChild',
    'flag:helpedOpposite',
    'flag:oppositeLeaving',
    'flag:helpedSchoolKid',
    'flag:schoolRumor',
    'flag:kidMask',
    'flag:wavedAcross',
    'flag:knockedNext',
    'flag:waitedNext',
    'flag:fedStairKid',
    'flag:signaledKid',
    'flag:stoppedLooking',
    'flag:watchedKid',
    'flag:sawEmptyWindow',
    'flag:helpedShaft',
    'flag:buildingList',
    'flag:heardBuildingMeet',
  ],
  ration: [
    'flag:ateEnough',
    'flag:hidRation',
    'flag:tossedBulge',
    'flag:setSchedule',
    'flag:foundStash',
    'flag:stockList',
    'flag:touchedRation',
    'flag:acceptedRation',
    'flag:rehearsedEmpty',
    'flag:sealedFood',
    'flag:saltedRice',
    'flag:lastCleanShirt',
  ],
  build: [
    'flag:hasPlywood',
    'flag:chargedUp',
    'flag:sharedOutage',
    'flag:powerList',
    'flag:mustWork',
    'flag:packMarks',
    'flag:tradedPower',
    'flag:bracedBalcony',
    'flag:abandonedBalcony',
    'flag:ignoredBalcony',
  ],
  outing: [
    'flag:gotCashOut',
    'flag:bankRun',
    'flag:withdrewTwice',
    'flag:lastParcel',
    'flag:stoleParcel',
    'flag:rewroteList',
    'flag:listHole',
    'flag:plannedNight',
    'flag:nightCalled',
    'flag:tookStairFood',
    'flag:usedFireExit',
    'flag:stairNote',
    'flag:tiptoedStair',
    'flag:hasEvacMap',
  ],
  ash: [
    'flag:baggedAsh',
    'flag:leftAsh',
    'flag:talkedLevy',
    'flag:sawDrop',
    'flag:sawHallSource',
    'flag:lateIodine',
    'flag:watchedNeck',
    'flag:ignoredNeck',
  ],
  list: [
    'flag:rentPaid',
    'flag:rentDelayed',
    'flag:mutedChat',
    'flag:savedNotices',
    'flag:keptScar',
    'flag:changedThesis',
    'flag:fixedCalendar',
    'flag:coveredMirror',
    'flag:answeredSlot',
    'flag:askedSlotWater',
  ],
  sleep: [
    'flag:quietSlept',
    'flag:permitSleep',
    'flag:sleptBathroom',
    'flag:usedBirthdayCandle',
    'flag:listenedPipe',
    'flag:tappedPipe',
    'flag:admittedHurt',
    'flag:lightPack',
    'flag:seenFlinch',
    'flag:darkCandle',
  ],
} as const;

export const ECHO_SLICE_FLAGS: string[] = Object.values(ECHO_CLUSTERS).flat();

export const ECHO_SLICE_EVENTS: EventFamily[] = [
  // 与 hook_echo_oldflags 同构，注释保留（2026-09 阶段化整理）
  /*
  {
    id: 'hook_echo_sliceflags',
    kind: 'story',
    intensity: 1,
    phase: ['prep', 'survival'],
    baseWeight: 4,
    cooldown: 14,
    variants: ALL_ECHO_FLAGS.map(echoVariant),
  },
  */
];
