import type { EventFamily, EventVariant } from '../../types';

const SLICE_FLAGS = [
  'flag:refusedChild',
  'flag:elevatorWarned',
  'flag:helpedOpposite',
  'flag:oppositeLeaving',
  'flag:rentPaid',
  'flag:rentDelayed',
  'flag:hasPlywood',
  'flag:gotCashOut',
  'flag:mutedChat',
  'flag:savedNotices',
  'flag:tankKey',
  'flag:tankAsked',
  'flag:stairLit',
  'flag:stairMarked',
  'flag:metRadioNeighbor',
  'flag:radioClip',
  'flag:helpedSchoolKid',
  'flag:schoolRumor',
  'flag:bankRun',
  'flag:kidMask',
  'flag:lastParcel',
  'flag:stoleParcel',
  'flag:chargedUp',
  'flag:sharedOutage',
  'flag:wavedAcross',
  'flag:curtainsDrawn',
  'flag:withdrewTwice',
  'flag:buildingList',
  'flag:heardBuildingMeet',
  'flag:filterReplaced',
  'flag:ateEnough',
  'flag:hidRation',
  'flag:quietSlept',
  'flag:gaveWaterOnce',
  'flag:liedNoWater',
  'flag:lentRope',
  'flag:bucketToilet',
  'flag:sealedToilet',
  'flag:lastCleanShirt',
  'flag:scannedBands',
  'flag:windowRetaped',
  'flag:tookStairFood',
  'flag:caughtDrip',
  'flag:tossedBulge',
  'flag:setSchedule',
  'flag:foundStash',
  'flag:stockList',
  'flag:knockedNext',
  'flag:waitedNext',
  'flag:sawHallSource',
  'flag:tradedPower',
  'flag:fixedCalendar',
  'flag:coveredMirror',
  'flag:answeredSlot',
  'flag:askedSlotWater',
  'flag:usedBirthdayCandle',
  'flag:sealedFood',
  'flag:saltedRice',
  'flag:baggedAsh',
  'flag:leftAsh',
  'flag:talkedLevy',
  'flag:bracedBalcony',
  'flag:abandonedBalcony',
  'flag:ignoredBalcony',
  'flag:sawDrop',
  'flag:usedFireExit',
  'flag:stairNote',
  'flag:tiptoedStair',
  'flag:fedStairKid',
  'flag:signaledKid',
  'flag:stoppedLooking',
  'flag:watchedKid',
  'flag:sawEmptyWindow',
  'flag:lateIodine',
  'flag:watchedNeck',
  'flag:ignoredNeck',
  'flag:copiedCoords',
  'flag:radioReplied',
  'flag:ignoredCoords',
  'flag:twoNorthStories',
  'flag:mappedClicks',
  'flag:sleptBathroom',
  'flag:helpedShaft',
  'flag:isolatedWater',
  'flag:hasEvacMap',
  'flag:drilledOnce',
  'flag:shoesOutside',
  'flag:rewroteList',
  'flag:listHole',
  'flag:plannedNight',
  'flag:nightCalled',
  'flag:bracedDoor',
  'flag:keptScar',
  'flag:permitSleep',
  'flag:changedThesis',
  'flag:touchedRation',
  'flag:acceptedRation',
  'flag:rehearsedEmpty',
  'flag:powerList',
  'flag:mustWork',
  'flag:packMarks',
  'flag:listenedPipe',
  'flag:tappedPipe',
  'flag:admittedHurt',
  'flag:lightPack',
  'flag:seenFlinch',
  'flag:darkCandle',
];

function echoVariant(flag: string): EventVariant {
  return {
    id: flag.replace(/^flag:/, ''),
    require: { all: [flag] },


    choices: [
      {
        id: 'ack',

        effect: { stats: { sanity: 2 },  tone: 'good' },
      },
      {
        id: 'skip',

        effect: { stats: { stamina: 4, sanity: -2 },  tone: 'neutral' },
      },
    ],
  };
}

export const ECHO_SLICE_EVENTS: EventFamily[] = [
  {
    id: 'hook_echo_sliceflags',
    kind: 'story',
    intensity: 1,
    phase: ['prep', 'survival'],
    baseWeight: 4,
    cooldown: 14,
    variants: SLICE_FLAGS.map(echoVariant),
  },
];
