import type { EventFamily } from '../../types';
import { beat, ch, skip } from './factory';

/** 备灾通用 + 公寓：囤货、房东、碘片、封窗、对门、物业、两份通报 */
export const PREP_SLICE_EVENTS: EventFamily[] = [
  beat({
    id: 'prep_slice_tape_windows',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { any: ['site:urban', 'site:highFloor'] },
    title: '五金店把封窗胶带摆到了最前面',
    body: '一卷蓝色的，一卷透明的。老板说透明的抗紫外线，蓝色的抗风。你问差别在哪，他耸肩："广告词不一样。"\n你住六楼。玻璃比门多。',
    choices: [
      ch('buy_both', '两卷都买', { res: { cash: -90, materials: 4 }, setFlags: ['flag:windowTaped'], log: '你把两卷胶带拎回家。塑料提手勒进手指。', tone: 'good' }, { requires: { res: { cash: 90 } } }),
      ch('blue', '只买抗风的', { res: { cash: -48, materials: 2 }, setFlags: ['flag:windowTaped'], log: '你买了蓝胶带。回家路上天阴了。', tone: 'good' }, { requires: { res: { cash: 48 } } }),
      skip('你没买。玻璃还是原来那几块。'),
    ],
  }),
  beat({
    id: 'prep_slice_elevator_notice',
    kind: 'social',
    phase: ['prep'],
    once: true,
    require: { all: ['site:highFloor'] },
    title: '电梯里贴了一张手写通知',
    body: '纸是从练习本上撕的，胶带粘了四个角。"物业停电检修，电梯或将停运，请预留步行时间。"没有日期，没有章。\n六楼。你已经在心里数台阶了。',
    choices: [
      ch('ask', '去物业问清楚', { stats: { stamina: -8, reputation: 2 }, setFlags: ['flag:elevatorWarned'], log: '值班的人说"上面让贴的"。你没得到日期。', tone: 'neutral' }),
      ch('water', '先把水往楼上搬', { res: { water: 8, cash: -40 }, stats: { stamina: -16 }, setFlags: ['flag:elevatorWarned'], log: '你爬了四趟。膝盖开始提意见。', tone: 'good' }, { requires: { res: { cash: 40 } } }),
      skip('你拍了张照片。通知还在，日期还是没有。'),
    ],
  }),
  beat({
    id: 'prep_slice_opposite_door',
    kind: 'social',
    phase: ['prep'],
    cooldown: 14,
    require: { all: ['site:urban'] },
    title: '对门在走廊里堆纸箱',
    body: '男的搬，女的数。小孩坐在门槛上抱着一只缺耳的兔子。他们看见你，点了下头，又继续搬。\n纸箱上写着"厨房"、"药品"、"不要压"。',
    choices: [
      ch('help', '帮他们抬一趟', { stats: { stamina: -10, humanity: 3, reputation: 4 }, world: { neighborhood: 6 }, setFlags: ['flag:helpedOpposite'], log: '你帮他们抬到电梯口。女的塞给你一包压缩饼干，说"备用"。', tone: 'good', res: { foodStaple: 2 } }),
      ch('ask_where', '问他们去哪', { stats: { reputation: 1 }, setFlags: ['flag:oppositeLeaving'], log: '男的顿了顿："北面。亲戚。你要是……算了。"他没说完。', tone: 'neutral' }),
      skip('你进了门。纸箱的声音隔着防盗门还能听见。'),
    ],
  }),
  beat({
    id: 'prep_slice_landlord_rent',
    kind: 'social',
    phase: ['prep'],
    once: true,
    require: { all: ['site:urban'] },
    title: '房东把催租发到了置顶',
    body: '就一行字："这个月别拖。现在这种时候，合同还是合同。"\n下面已经有人在骂。也有人在转账截图。',
    choices: [
      ch('pay', '先把房租打过去', { res: { cash: -2800 }, stats: { sanity: 4 }, setFlags: ['flag:rentPaid'], log: '你转了账。房东回了一个"收到"。世界暂时还按旧规矩转。', tone: 'neutral' }, { requires: { res: { cash: 2800 } } }),
      ch('delay', '回消息说缓几天', { stats: { reputation: -4, sanity: -3 }, setFlags: ['flag:rentDelayed'], log: '他已读不回。你把对话往上滑，看见上个月的"谢谢"。', tone: 'bad' }),
      skip('你把聊天窗口划掉了。房租还在原处。', { stats: { sanity: -4 } }),
    ],
  }),
  beat({
    id: 'prep_slice_iodine_rumor',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    title: '药店门口有人在发传单',
    body: '传单上印着一颗甲状腺，和一行加粗的字："现在买碘片的都是傻子，辐射 fortification 是谣言。"英文拼错了。\n柜台里面，碘片的价签被手写改过两次。',
    choices: [
      ch('buy', '还是买一盒', { res: { cash: -180, meds: 2 }, setFlags: ['flag:iodine', 'flag:iodineDoubt'], log: '你买了。传单被你揉成一团。你不确定谁在撒谎。', tone: 'good' }, { requires: { res: { cash: 180 } } }),
      ch('argue', '当场拆穿拼写', { stats: { reputation: 3, sanity: 2 }, setFlags: ['flag:iodineDoubt'], log: '发传单的人走了。药店老板看了你一眼，把价签又改高了一点。', tone: 'neutral' }),
      skip('你没买，也没问。传单在风里翻。'),
    ],
  }),
  beat({
    id: 'prep_slice_pharmacy_queue',
    kind: 'opportunity',
    phase: ['prep'],
    cooldown: 14,
    title: '药店限购：每人两盒退烧药',
    body: '队伍从门口排到公交站。有人拿着户口本，有人拿着别人的医保卡。店员喊："没处方的退烧药也算两盒！"\n你口袋里有一张旧处方，日期是去年的。',
    choices: [
      ch('queue', '排队买满额', { res: { cash: -120, meds: 4 }, stats: { stamina: -8 }, log: '你买到了两盒。出门时听见后面有人说"他是不是来过"。', tone: 'good' }, { requires: { res: { cash: 120 } } }),
      ch('script', '用旧处方再买一次', { res: { cash: -200, meds: 7 }, stats: { reputation: -6, humanity: -2 }, setFlags: ['flag:fakeScript'], log: '店员看了一眼日期，还是扫了码。你没有停留。', tone: 'grim' }, { requires: { res: { cash: 200 } } }),
      skip('你离开了。队伍没有变短。'),
    ],
  }),
  beat({
    id: 'prep_slice_plywood',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { any: ['site:urban', 'site:highFloor'] },
    title: '木材市场把最后几张多层板立在路边',
    body: '老板说按张卖，不议价，现金。板子边角已经有人用笔画了尺寸。\n你量过窗户。差不多。你量过门。也差不多。',
    choices: [
      ch('buy', '买两张扛回家', { res: { cash: -360, materials: 8 }, stats: { stamina: -18 }, setFlags: ['flag:hasPlywood'], log: '你把板子竖在电梯里。有人侧身让你，有人皱眉。', tone: 'good' }, { requires: { res: { cash: 360 } } }),
      ch('one', '只买一张挡最大的窗', { res: { cash: -180, materials: 4 }, stats: { stamina: -10 }, setFlags: ['flag:hasPlywood'], log: '一张。你回家对着窗户比了比，还缺一截。', tone: 'good' }, { requires: { res: { cash: 180 } } }),
      skip('你记下价格。明天可能没有了。'),
    ],
  }),
  beat({
    id: 'prep_slice_atm',
    kind: 'threat',
    intensity: 3,
    phase: ['prep'],
    once: true,
    title: '楼下柜员机吐了一半就停了',
    body: '屏幕还亮着，卡还在里面。后面的人开始拍机器，拍玻璃，拍那个已经走开的保安。\n你的卡在钱包里。你还没插。',
    choices: [
      ch('wait', '等机器恢复再取', { res: { cash: 2000 }, stats: { stamina: -12, sanity: -4 }, setFlags: ['flag:gotCashOut'], log: '二十分钟后它又吐了一次。你取到了限额。队伍散了一半。', tone: 'good' }),
      ch('leave_card', '帮那张卡住的卡取出来交给保安', { stats: { humanity: 4, reputation: 3, sanity: 2 }, world: { neighborhood: 4 }, log: '保安说谢谢，把卡锁进抽屉。你没取到钱。', tone: 'good' }),
      skip('你离开了。身后有东西被砸裂的声音。', { world: { lawOrder: -2 }, stats: { sanity: -3 } }),
    ],
  }),
  beat({
    id: 'prep_slice_groupchat',
    kind: 'social',
    phase: ['prep'],
    cooldown: 14,
    title: '业主群一天内来了四十条通报',
    body: '居委会说不必囤水。街道说可以适量。有人转发外网截图，有人骂转发的人。管理员把群名改成了"请勿恐慌"。\n两条置顶互相打架。',
    choices: [
      ch('mute', '全部静音', { stats: { sanity: 6 }, setFlags: ['flag:mutedChat'], log: '世界安静了一点。你不知道自己是不是错过了真的那条。', tone: 'neutral' }),
      ch('save', '把互相矛盾的通报存下来', { stats: { sanity: -2 }, setFlags: ['flag:savedNotices', 'flag:assumeWorst'], log: '你截了屏。两份图并排放着，像在等你选边。', tone: 'neutral' }),
      skip('你往上滑，看见上个月谁家猫丢了。'),
    ],
  }),
  beat({
    id: 'prep_slice_tank_key',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { all: ['site:highFloor'] },
    title: '顶楼水箱间的钥匙在门卫室挂着',
    body: '门卫老周抽烟，说"上面不让借"。烟灰掉在登记本上。钥匙就在他脑后的钉子上，标签写着"6F 水箱，勿外借"。',
    choices: [
      ch('bribe', '塞一包烟把钥匙"借"一晚', { res: { cash: -60, water: 8 }, stats: { reputation: -2 }, setFlags: ['flag:tankKey'], log: '老周没点头，也没拦。钥匙在你掌心是温的。你连夜灌了两桶。', tone: 'good' }, { requires: { res: { cash: 60 } } }),
      ch('talk', '跟他讲你只想提前灌桶', { stats: { reputation: 2 }, setFlags: ['flag:tankAsked'], log: '他说"等通知"。通知从来都比水先停。', tone: 'neutral' }, { requires: { skills: { negotiation: 2 }, reason: '需要谈判 2 级' } }),
      skip('你没开口。钉子上的钥匙轻轻转了一下。'),
    ],
  }),
  beat({
    id: 'prep_slice_stair_light',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { all: ['site:highFloor'] },
    title: '楼道感应灯坏了两层',
    body: '四楼到六楼是黑的。你用手电照台阶，看见有人用粉笔写了"慢走"。\n物业说配件在采购。采购这两个字你这周听了太多次。',
    choices: [
      ch('fix', '自己换灯', { res: { parts: -1, cash: -40 }, stats: { stamina: -8, reputation: 4 }, skills: { mechanics: 1 }, setFlags: ['flag:stairLit'], log: '灯亮了。下楼的人抬头看了你一眼。', tone: 'good' }, { requires: { res: { parts: 1, cash: 40 } } }),
      ch('tape', '在扶手上贴反光条', { res: { materials: -1 }, setFlags: ['flag:stairMarked'], log: '你贴了反光条。黑还是黑，但手知道该往哪放。', tone: 'good' }, { requires: { res: { materials: 1 } } }),
      skip('你用手机照着爬回去。电池掉了四格。', { stats: { stamina: -6 } }),
    ],
  }),
  beat({
    id: 'prep_slice_neighbor_radio',
    kind: 'social',
    phase: ['prep'],
    once: true,
    require: { all: ['site:urban'] },
    title: '五楼有人把收音机开得很大',
    body: '短波里的杂音，和一句断断续续的"……不要出门……碘……"。\n你隔着楼板听见有人把音量又拧大了一档。',
    choices: [
      ch('knock', '去敲五楼的门', { stats: { stamina: -4, reputation: 2 }, setFlags: ['flag:metRadioNeighbor'], log: '开门的是个戴眼镜的男人。他让你抄了一组频率。', tone: 'good' }),
      ch('record', '在门口用手机录音', { stats: { sanity: -2 }, setFlags: ['flag:radioClip'], log: '你录了四十秒。回放的时候，"碘"那一个字反而听不清了。', tone: 'neutral' }),
      skip('你把电视打开，盖过楼板。'),
    ],
  }),
  beat({
    id: 'prep_slice_school_gate',
    kind: 'social',
    phase: ['prep'],
    once: true,
    title: '小学门口提早放学，家长堵在路上',
    body: '老师说接到"天气原因"。天空是普通的阴。有个孩子问能不能明天再来，没人回答。\n你路过，不是来接谁的。',
    choices: [
      ch('help_kid', '把走散的小孩送到老师那里', { stats: { humanity: 4, stamina: -6 }, world: { neighborhood: 3 }, setFlags: ['flag:helpedSchoolKid'], log: '老师说谢谢。孩子的手是热的。你自己的手不是。', tone: 'good' }),
      ch('ask_teacher', '问老师接到的是谁的通知', { stats: { sanity: -3 }, setFlags: ['flag:schoolRumor'], log: '她摇头。她的工牌还别着笑脸。', tone: 'neutral' }),
      skip('你绕开人群。车喇叭一声接一声。'),
    ],
  }),
  beat({
    id: 'prep_slice_bank_line',
    kind: 'threat',
    intensity: 2,
    phase: ['prep'],
    once: true,
    title: '银行门口有人开始推搡',
    body: '取号机没纸了。大堂经理反复说系统正常。你看见有人把行李箱立在队伍里占位。\n你来是想把活期转成现金。',
    choices: [
      ch('cash', '挤进去把能取的都取了', { res: { cash: 3500 }, stats: { stamina: -14, reputation: -4, sanity: -5 }, setFlags: ['flag:bankRun'], log: '你取到了。出门时有人撞了你的肩。你没有回头。', tone: 'good' }),
      ch('leave', '改天再来', { stats: { sanity: 2 }, log: '你走了。回头看见队伍拐过了街角。', tone: 'neutral' }),
      skip('你站了一会儿，直到自己也开始生气，然后离开。', { stats: { sanity: -4, humanity: -1 } }),
    ],
  }),
  beat({
    id: 'prep_slice_mask_gone',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    title: '便利店口罩货架空了，只剩儿童款',
    body: '店员说早上还有。儿童款是粉色的，印着卡通。你比了比，能戴，不好看。\n门口有人问你"还有没有"。',
    choices: [
      ch('buy_kids', '把儿童款都买走', { res: { cash: -80 }, setFlags: ['flag:mask', 'flag:kidMask'], log: '你买了。粉色勒着耳朵。门口那个人看了你的袋子一眼。', tone: 'good' }, { requires: { res: { cash: 80 } } }),
      ch('share', '留给问你的人一盒', { res: { cash: -40 }, stats: { humanity: 3, reputation: 2 }, setFlags: ['flag:mask'], log: '你自己留一盒，给她一盒。她说她有孩子。你没有问。', tone: 'good' }, { requires: { res: { cash: 40 } } }),
      skip('你没买。卡通眼睛还在货架上瞪着。'),
    ],
  }),
  beat({
    id: 'prep_slice_last_delivery',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { all: ['site:urban'] },
    title: '快递员说这是他这片最后一趟',
    body: '他靠在电动车上抽烟，车斗里只剩两件。一件是你三天前下的米，一件写着别人的名字。\n他说站点明天停。',
    choices: [
      ch('take', '签收你的米', { res: { foodStaple: 10 }, stats: { sanity: 3 }, setFlags: ['flag:lastParcel'], log: '米很沉。他骑走之前说"别下单了"。', tone: 'good' }),
      ch('other', '把那件别人的也留下，说你认识', { res: { foodStaple: 10, meds: 2 }, stats: { humanity: -4, reputation: -3 }, setFlags: ['flag:stoleParcel'], log: '你签了两个名。其中一个不是你的。', tone: 'grim' }),
      ch('own_only', '只要自己的那件', { res: { foodStaple: 10 }, log: '你让他把别人的那件带走。你的米你拿走了。', tone: 'good' }),
    ],
  }),
  beat({
    id: 'prep_slice_power_notice',
    kind: 'weather',
    phase: ['prep'],
    once: true,
    title: '电梯轿厢里多了一张停电预告',
    body: '印刷的，有公章，时间写着"视情况"。下面有人用笔加了一句："就是要停。"\n你按六楼。数字跳得很慢。',
    choices: [
      ch('charge', '回家把所有电池充满', { stats: { stamina: -6 }, wear: { batteryCharge: 8 }, setFlags: ['flag:chargedUp'], log: '你把充电宝、手电、收音机都插上。插排发烫。', tone: 'good' }),
      ch('print', '把预告拍下来发到群里', { stats: { reputation: 2 }, world: { neighborhood: 2 }, setFlags: ['flag:sharedOutage'], log: '有人骂你制造恐慌。有人问你插座借不借。', tone: 'neutral' }),
      skip('你出了电梯。预告还在，字还是那几个。'),
    ],
  }),
  beat({
    id: 'prep_slice_measure_glass',
    kind: 'opportunity',
    phase: ['prep'],
    once: true,
    require: { all: ['site:highFloor'] },
    title: '你开始给每扇窗编号',
    body: '客厅两扇，卧室一扇，厨房那扇打不开。你用纸条贴在框上：A、B、C、D。\nD 对着对面楼。对面有人站在窗前，也在量什么。',
    choices: [
      ch('wave', '朝对面挥一下手', { stats: { sanity: 3, humanity: 1 }, setFlags: ['flag:wavedAcross'], log: '对面也挥了。然后把窗帘拉上了。', tone: 'good' }),
      ch('close', '先把窗帘全部拉严', { stats: { sanity: -2 }, world: { exposure: -4 }, setFlags: ['flag:curtainsDrawn'], log: '屋子暗下来。你仍然记得对面那个人的轮廓。', tone: 'neutral' }),
      skip('你写完编号。纸条在气流里动。'),
    ],
  }),
  beat({
    id: 'prep_slice_withdraw_more',
    kind: 'opportunity',
    phase: ['prep'],
    cooldown: 14,
    title: '同事拉你去另一家银行排队',
    body: '他说这家限额高。你看看表，下午还要去超市。队伍从大堂排到了阳光里。\n他已经站了四十分钟，把位置分你一半。',
    choices: [
      ch('join', '一起排', { res: { cash: 2500 }, stats: { stamina: -16, reputation: 2 }, setFlags: ['flag:withdrewTwice'], log: '你又取到一笔。同事说"够了吧"。你不知道够是多少。', tone: 'good' }),
      ch('shop', '去超市，把位置让回去', { stats: { humanity: 2 }, log: '你去超市了。晚上他发来一张空货架的照片。', tone: 'neutral' }),
      skip('你两边都没去成。回到家，手是空的。', { stats: { sanity: -3 } }),
    ],
  }),
  beat({
    id: 'prep_slice_building_meet',
    kind: 'social',
    intensity: 3,
    phase: ['prep'],
    once: true,
    require: { all: ['site:urban'] },
    title: '一楼大堂有人在召集"楼栋互助"',
    body: '发起人是 3 楼的，拿着本子记名字。有人问谁来分配物资，当场吵起来。\n本子已经有十几个名字。没有你的。',
    choices: [
      ch('join', '写上名字', { stats: { reputation: 4, humanity: 2 }, world: { neighborhood: 8, exposure: 6 }, setFlags: ['flag:buildingList'], log: '你写了。名字在纸上看起来比你本人更镇定。', tone: 'good' }),
      ch('watch', '听完不签字', { stats: { sanity: -2 }, setFlags: ['flag:heardBuildingMeet'], log: '你听完了。分配的事没有结论。本子被合上。', tone: 'neutral' }),
      skip('你从边门上楼。吵闹声跟着楼梯转了一圈。'),
    ],
  }),
];
