import type { Site, SiteId } from '../types';

/**
 * 站点：Day 1 的第一个重大决策。
 *
 * 每个站点不只是数值差异，它的 tags 会直接进入事件过滤器——
 * 所以选在地下停车场，你从此不会遇到"有人从窗户翻进来"，
 * 但会遇到"有人在通风井上方喊话，威胁往里灌汽油"。
 */
export const SITES: Site[] = [
  {
    id: 'apartment',
    name: '自家公寓',
    codename: 'HOME-6F',
    desc: '你住了六年的六楼两居室。防盗门是租房时就有的老货，窗外是整座城市。你知道哪块地板会响，也知道楼下便利店几点上货。',
    cost: {},
    baseModules: {},
    caps: { fortify: 2, conceal: 1, cistern: 1, filter: 3, power: 2, insulate: 2, airFilter: 3, medbay: 3, garden: 1, radio: 3 },
    tags: ['site:urban', 'site:highFloor'],
    lootMult: 1.2,
    travelFuel: 0,
    travelStamina: 5,
    exposureBase: 12,
    companionCap: 0,
    waterCapMult: 0.75,
    pros: ['市中心，搜刮效率 +20%', '邻居社区已有交情', '外出不耗燃料'],
    cons: ['楼板承重有限，储水上限很低', '加固最多到 2 级', '停电后每次外出都要爬六层', '窗户太多，藏不住'],
  },
  {
    id: 'bungalow',
    name: '老城平房',
    wip: true,
    codename: 'YARD-01',
    desc: '城南待拆迁的一片平房，你姑妈留下的。院子里有口废弃的压水井和一棵石榴树。墙是空心砖，一脚能踹穿，但地是你的。',
    cost: { cash: 6000, ap: 1 },
    baseModules: { garden: 1 },
    caps: { fortify: 2, conceal: 2, cistern: 3, filter: 3, power: 3, insulate: 2, airFilter: 2, medbay: 3, garden: 3, radio: 3 },
    tags: ['site:urban', 'site:groundLevel', 'site:hasYard'],
    lootMult: 1.0,
    travelFuel: 0.5,
    travelStamina: 3,
    exposureBase: 16,
    companionCap: 4,
    waterCapMult: 1.2,
    pros: ['有院子，可挖地窖、可大面积种植', '储水容量 +20%', '自带 1 级农圃', '可打井取水'],
    cons: ['空心砖墙，加固上限 2 级', '门窗多，正面暴露', '声音传得远'],
  },
  {
    id: 'garage',
    name: '地下车库 B2',
    wip: true,
    codename: 'SUB-B2',
    desc: '小区地下负二层的一个角落，物业主任姓陈，抽烟。这里没有一丝自然光，常年十六度，混凝土顶板厚得能挡住很多东西——包括信号，也包括逃生的机会。',
    cost: { cash: 12000, ap: 1, requires: { skills: { negotiation: 2 }, reason: '需要谈判 2 级说服物业' } },
    baseModules: { insulate: 2, conceal: 1 },
    caps: { fortify: 3, conceal: 3, cistern: 2, filter: 2, power: 3, insulate: 3, airFilter: 3, medbay: 2, garden: 1, radio: 1 },
    tags: ['site:urban', 'site:underground', 'site:noSunlight', 'site:floodRisk'],
    lootMult: 1.1,
    travelFuel: 0.3,
    travelStamina: 3,
    exposureBase: 6,
    companionCap: 4,
    waterCapMult: 1.0,
    pros: ['混凝土顶板：天然辐射屏蔽', '恒温，自带 2 级保温', '隐蔽性极佳，暴露度基础值最低', '加固可达 3 级'],
    cons: ['没有自然光，农圃必须靠电补光', '通风极差，空气过滤是刚需', '内涝会致命', '无线电最多 1 级'],
  },
  {
    id: 'farmhouse',
    name: '郊区农舍',
    wip: true,
    codename: 'RURAL-7',
    desc: '离城四十公里，你爸的老宅。有井、有地、有个塌了一半的猪圈。最近的邻居在两公里外。这里没人会来打劫你——因为也没人会来救你。',
    cost: { cash: 20000, ap: 2, requires: { tags: { all: ['hasVehicle'] }, reason: '需要一辆车才能搬过去' } },
    baseModules: { garden: 1, cistern: 1, filter: 1 },
    caps: { fortify: 2, conceal: 3, cistern: 3, filter: 3, power: 3, insulate: 2, airFilter: 2, medbay: 3, garden: 3, radio: 3 },
    tags: ['site:isolated', 'site:groundLevel', 'site:hasYard', 'site:hasWell'],
    lootMult: 0.7,
    travelFuel: 2.5,
    travelStamina: 11,
    exposureBase: 4,
    companionCap: 4,
    waterCapMult: 1.5,
    pros: ['有水井，自带净水与储水', '大片土地，农圃可达 3 级', '远离人群，几乎不会被袭击', '储水容量 +50%'],
    cons: ['搜刮产出只有 70%，且每趟烧 2.5 L 油', '孤立无援，没有邻居预警', '冬天更冷', '搬迁需要车'],
  },
  {
    id: 'bunker',
    name: '废弃人防工程',
    wip: true,
    codename: 'CD-1971',
    desc: '七十年代挖的防空洞，入口藏在一间关了很久的修车铺后面。铁门锈住了，里面滴水，墙上还留着褪色的标语。它为一场没有发生的战争而建，现在终于要派上用场。',
    unlock: 'site_bunker',
    cost: { cash: 4000, ap: 2, requires: { res: { parts: 10 }, reason: '锈死的闸门与通风机需要 10 零件才能修复' } },
    baseModules: { fortify: 2, conceal: 3, insulate: 2 },
    caps: { fortify: 3, conceal: 3, cistern: 2, filter: 2, power: 2, insulate: 3, airFilter: 3, medbay: 2, garden: 1, radio: 2 },
    tags: ['site:underground', 'site:damp', 'site:noSignal', 'site:noSunlight'],
    lootMult: 0.9,
    travelFuel: 0.6,
    travelStamina: 6,
    exposureBase: 2,
    companionCap: 4,
    waterCapMult: 1.0,
    pros: ['自带 2 级加固与满级隐蔽', '几乎不可能被发现', '厚土层，对辐射和尘暴都有效'],
    cons: ['潮湿，有霉菌性肺病风险', '无信号，无线电需要架外置天线', '入口修复要先花 10 零件', '发电上限只有 2 级'],
  },
  {
    id: 'watertower',
    name: '山腰水塔',
    wip: true,
    codename: 'TOWER-N',
    desc: '北山半坡上一座停用的市政水塔。爬上去要走三百级铁梯，但站在顶上，你能看见整条进城的公路——以及任何朝你走来的人。',
    unlock: 'site_watertower',
    cost: { cash: 9000, ap: 2, requires: { tags: { all: ['hasVehicle'] }, reason: '需要车才能把物资运上山' } },
    baseModules: { cistern: 3, conceal: 1 },
    caps: { fortify: 2, conceal: 2, cistern: 3, filter: 3, power: 2, insulate: 1, airFilter: 2, medbay: 1, garden: 1, radio: 3 },
    tags: ['site:elevated', 'site:isolated', 'site:cramped'],
    lootMult: 0.6,
    travelFuel: 1.8,
    travelStamina: 13,
    exposureBase: 8,
    companionCap: 1,
    waterCapMult: 2.0,
    pros: ['满级储水，容量翻倍', '视野极佳：所有袭击都会提前一天预警', '重力供水，净水不耗电', '无线电信号极好'],
    cons: ['空间狭小，最多只能收留 1 人', '保温上限 1 级，风雪直接打在铁皮上', '搜刮产出只有 60%', '每天上下山极耗体力'],
  },
];

export const SITE_BY_ID: Record<SiteId, Site> = Object.fromEntries(SITES.map((s) => [s.id, s])) as Record<SiteId, Site>;

export function getSite(id: SiteId | null): Site | null {
  return id ? SITE_BY_ID[id] ?? null : null;
}
