import { registerTree } from '../t';

export const data = {
  cause: {
    rationFull: '充足口粮',
    rationLow: '口粮不足',
    ration: '口粮',
    waterFull: '充足饮水',
    waterLow: '饮水限量',
    water: '饮水',
    hunger: '饥饿',
    thirst: '脱水',
    cold: '失温',
    air: '吸入污染物',
    radiation: '辐射',
    sanity: '精神崩溃',
    raid: '袭击',
    abandon: '放弃',
  },
  garden: { yield: '农圃：生鲜 +{amt} 份' },
  filter: {
    tankCleaning: '净水：水箱在清洗，产出没法入库',
    rainStored: '净水：接雨雪 +{stored} L{overflow}',
    wellStored: '净水：井水过滤 +{stored} L{overflow}',
    overflowBit: '（桶满，溢出 {wasted} L）',
    allOverflow: '净水产出 {amt} L，但储水已满，全部溢出',
    building: '净水在施工，这场雨接不住',
    clogged: '滤芯堵死，这场雨接不住',
    noPower: '净水没电，这场雨接不住',
    noModule: '外面在下雨，但没有净水设备，接不住',
    dead: '滤芯：已堵死，净水与空气过滤失效',
    daysLeft: '滤芯：还剩约 {days} 天',
  },
  fridge: {
    on: '冰箱还在转：生鲜 −{amt} 份',
    off: '冰箱没电：生鲜 −{amt} 份',
  },
  ration: {
    recycle:
      '没下雨，净水走回用（过滤尿液/废水，今日耗水 ×{mult}）：饮水 −{used} L（需求 {need} / 库存还剩 {left}）',
    water: '配给：饮水 −{used} L（需求 {need} / 库存还剩 {left}）',
    dirty: '饮水不足：只能喝没处理过的水',
    foodBits: '{kind} {amt}',
    food: '配给：食物 −{amt} 份（{bits}）',
    foodZero: '配给：食物 −0 份（需求 {need}）',
    waterGap: '饮水缺口：{pct}%',
    foodGap: '食物缺口：{pct}%',
    fresh: '生鲜',
    staple: '罐头',
  },
  power: {
    solar: '天气光伏：+{solar} kWh{weather}',
    weatherBit: '（天气 ×{mult}）',
    gridBit: ' · 市电 +{amt}',
    genBit: ' · 柴油机补 +{amt}',
    offline: '缺电停摆：{list}',
    fuel: '柴油机：燃料 −{amt} L',
    oilWarn: '发电机开始异响：需要保养',
    battDischarge: '蓄电池放电 −{amt} kWh（余 {left}/{cap}）',
    battCharge: '蓄电池充电 +{amt} kWh（{left}/{cap}）',
    battIdle: '蓄电池待命 {stored}/{cap} kWh',
  },
  heat: {
    fuelNoInsulate: '想烧燃料取暖，但保温不到 1 级，装不了炉子：室内 {indoor}°C',
    alreadyWarm: '屋里已经够暖，不用烧：室内 {indoor}°C',
    fuelEmpty: '想烧燃料取暖，但没有油了：室内 {indoor}°C',
    fuelBurn: '烧燃料取暖：燃料 −{spent} L，室内 {indoor}°C',
    elecLocked: '想用电热，但还没达到保温 2 级且发电 1 级：室内 {indoor}°C',
    elecOn: '电热开了一夜：室内 {indoor}°C',
    elecFail: '电热没排上或没电：室内 {indoor}°C',
    off: '不取暖：室内 {indoor}°C',
  },
  buy: {
    notShop: '这里不能采购',
    limit: '已达今日限购',
    waterFull: '储水已满（上限 {cap} L）',
    empty: '货架已经空了',
    noCash: '现金不够',
    iodineShop: '只有药店卖碘片',
    iodineGone: '柜台只剩这两盒，你已经买过了',
    haulNoWater: '储水已满（上限 {cap} L），水没装下',
    haulPartial: '只装了 {take} L 水，桶满了',
  },
  health: {
    starveStart: '你开始挨饿',
    thirstStart: '你开始脱水',
    malnourish: '长期节食开始留下痕迹：营养不良',
    foodHeal: '{name}：因口粮恢复而好转',
    waterHeal: '{name}：因饮水恢复而好转',
    healed: '{name}：好转了',
    worsen: '{from}恶化为{to}',
    dysenteryJaundice: '痢疾拖了太久，眼白开始发黄',
    cold: '保温不足：室内 {felt}°C，当前配置只能扛到 {floor}°C',
    hypo: '你出现了失温症状',
    air: '空气污染 {pollution}：超出防护 {over}',
    co: '屋里密不透风，炉子烧了一夜——你在头痛中醒来',
    coLog: '密封做得太好了。你忘了燃烧要消耗氧气，也会产生别的东西。',
    filterOff: '空气过滤缺电停摆：辐射屏蔽按未开机计算',
    radSickness: '你开始呕吐，牙龈在渗血',
    rad: '辐射屏蔽不足：辐射 {rad}，只能挡到 {tol}（生命 {dmg}）',
    iodineEnd: '碘片保护今晚到期：明天甲状腺要自己扛',
    lightsOn: '灯开着：理智 +{amt}',
    lightsOff: '灯关着：理智 {amt}',
    dirtyWater: '那口水的代价来得很快',
    giardia: '肚子开始绞痛，滤过的水也不干净',
    filterDysentery: '滤过的水仍让你跑了两趟卫生间',
    flu: '你开始发烧',
    mold: '潮湿终于收了它的租：你开始咳嗽',
    hygiene: '卫生条件太差：{name}',
    despair: '你已经不太确定明天为什么要起床',
    medbayCold: '医疗站过夜，但屋里太冷，恢复打了折扣',
    medbayFull: '医疗站过夜：体力 +{sta}，理智 +{san}',
    medbaySta: '医疗站过夜：体力 +{sta}',
    treatNo: '这个状态没法用药解决',
    treatMedbay: '需要 {lvl} 级医疗站',
    treatMeds: '需要 {cost} 组药品',
  },
  req: {
    res: '缺 {short} {name}',
    stats: '状态不足',
    skill: '需要{name} {need} 级',
    modules: '避难所设施不足',
    ap: '需要 {ap} 行动点',
    tags: '条件不满足',
  },
  effect: {
    ap: '行动点 {delta}',
    condAdd: '获得状态：{name}',
    condRemove: '解除状态：{name}',
    moduleUp: '{name} → {lvl} 级',
    moduleDown: '{name}受损 → {lvl} 级',
    battery: '蓄电 {shown} kWh（{stored}/{cap}）',
    exposure: '暴露度 {delta}',
    join: '{name} 加入了你',
    full: '已经住不下更多人了',
    leave: '{name} 离开了',
    north: '北上路线已知',
    flagged: '已记入日记',
    stock: '{name} 存量变为 {pct}%',
    blocked: '地图：{name} 设卡（{why}）',
    sequelWait: '续篇将在你【{hooks}】之后出现',
    sequel: '这件事还没有结束',
  },
  build: {
    capSite: '{site}的条件限制，{module}最高只能到 {cap} 级',
    queued: '已在施工队列中',
    atCap: '已达上限',
    cannot: '无法升级',
    needModule: '需要先把{module}升到 {lvl} 级',
    gardenLight: '这里没有自然光，2 级以上农圃需要 2 级发电供补光灯',
    radioSignal: '此处无信号，需要先架设外置天线（额外 6 零件）',
    lackMat: '缺 {n} 建材',
    lackParts: '缺 {n} 零件',
    lackCash: '缺 {n} 元',
    diyCost: '{mat} 建材 · {parts} 零件 · {labor} 工时',
    noHire: '已经没有人接活了',
    hireCost: '{cash} 元 · 1 行动点 · 2 天完工',
    noBuy: '物流已经停了',
    buyCost: '{cash} 元 · {days} 天到货 · 约 {pct}% 概率收不到',
    cannotStart: '无法开工',
    needAp: '需要 1 行动点',
    startDiy: '开始动工：{name} → {target} 级。{penalty}',
    startHire: '雇了施工队做{name}，说是两天完工。钱已经付了。',
    startBuy: '下单了{name}的成品设备，{days} 天后到货。',
    noProject: '没有这个工程',
    notDiy: '这个工程不需要你动手',
    noAp: '行动点不足',
    failHurt: '做坏了，浪费 {n} 建材，还划伤了手。',
    failWaste: '尺寸没对上，浪费了 {n} 建材。',
    labor: '投入 {gain} 工时（{done}/{total}）',
    companion: '同伴投入了 {n} 工时',
    done: '{name}完工，达到 {lvl} 级',
    noDelivery: '{name}的货没到',
    noDeliveryLog: '你订的{name}没有到。客服电话是空号，物流单号查不到。钱是真的付了。',
    doneLog: '{name}完工了。{desc}',
    cancel: '{name}的工程停了。拆下来的材料只回收了一半。',
    maintFilter: '更换滤芯',
    maintFilterDesc: '净水与空气过滤共用同一套耗材。用尽之后两个模块会同时失效。',
    maintNoFilter: '还没有需要滤芯的设备',
    maintOil: '保养发电机',
    maintOilDesc: '机油、空气滤清、皮带。不保养就会在最不该的时候停。',
    maintNoGen: '还没有柴油发电机组',
    filterDone: '滤芯寿命恢复到 {days} 天',
    oilDone: '发电机组安静了下来',
    salvagePrep: '现在还买得到东西，没必要拆房子',
    salvageOut: '拆出 {mat} 建材、{parts} 零件。暴露度 +{exp}。',
    noTarget: '没有这个目标',
  },
  salvage: {
    furniture: { name: '拆自己的家具', desc: '衣柜、书架、床板。你亲手装的，现在亲手拆掉。' },
    car: { name: '拆一辆废弃汽车', desc: '电瓶、线束、皮带、后备箱的千斤顶。要用到电动工具，很响。' },
    empty_flat: {
      name: '撬开邻居的空房',
      desc: '对门那家早就走了。门是锁着的，但门框是木头的。你知道楼里还有人在看着。',
    },
    public: { name: '拆公共设施', desc: '楼道扶手、消防箱、配电间的铜线。理论上这些属于所有人。' },
  },
  exposure: {
    siteBase: '{site}基础',
    lights: '灯光漏出窗外',
    generator: '柴油机噪音',
    crew: '{n} 名同伴的动静',
    conceal: '{lvl} 级隐蔽',
    concealBuild: '隐蔽施工中，材料堆在门口',
    weather: '天气掩盖了行踪',
    gunshot: '前几天的枪声',
    raidHoldBuild: '门框还没装好，但你用能搬得动的一切把入口堵住了。他们试了很久，最后走了。',
    raidHold: '门挡住了。你听着外面的动静，一直到脚步声散开。',
    raidFailBuild: '半拆的门框一脚就开了。你藏在里屋，听着他们把能拿的都拿走。',
    raidFail: '门开了。他们进了屋。',
  },
  run: {
    intro: '新闻里那条消息你已经刷到第四遍了。前三遍你都当成了噪音。这一遍你放下了手机，开始算家里还有多少水。',
    noSite: '没有这个站点',
    siteWip: '这个住所还在开发中',
    needCash: '需要 {cash} 元',
    needCar: '需要一辆车',
    choseSite: '你决定把这里作为据点：{name}。{desc}。',
    noAp: '行动点不足',
    intelStale: '这条情报已经过时了',
    intelDone: '已经核实过',
    price: '物价指数：升到 {idx}',
    secret: '有人终于说了实话（见日记）',
    exposureDecay: '夜里动静散了一些：暴露度 −{n}',
    storyLive: '（叙事模式）你本该死在这一天。',
    iodineEnd: '碘片的保护过期了。甲状腺又暴露在外面。',
    cannot: '现在做不到这一步',
    stolen: '物资被抢走了一部分',
    ammo: '消耗弹药 {n} 发',
    moduleBroke: '{name}被破坏，等级下降',
    storyRaid: '（叙事模式）袭击本可以要了你的命。',
    missed: '有件事错过了时机，没有再出现。',
    orphan: '{n} 件事没有下文，像是被谁忘了。',
  },
  ending: {
    days: '存活 {n} 天',
    collapse: '撑过了崩溃日',
    threat: '末世等级 {n}',
    families: '首次遭遇 {n} 类事件',
    ending: '结局：{name}',
    newEnding: '发现新结局',
    diff: '难度修正 ×{mult}',
  },
  collapse: {
    moduleHit: '{name}已到 {lvl} 级，这正是这场灾难最需要的',
    moduleMiss: '{name}还是 0 级，而它是这场灾难的核心防线',
    iodineHit: '你备了碘片。接下来几天，它会替你的甲状腺挡下大部分剂量',
    iodineSaw: '没有碘片。药店里那两盒你没买',
    iodineMiss: '你没备碘片。核沉降对甲状腺不客气',
    underground: '你在地下。混凝土顶板是最诚实的屏蔽',
    highFloor: '六楼。你离沉降物比任何人都近',
    floodRisk: '你选了会内涝的地方。水正在往下走，而你在最下面',
    elevated: '你在高处。这一次，高度就是一切',
    noFilter: '没有空气过滤。你唯一的防线是一包一次性口罩',
    sealed: '密封做得不错，外面的东西进不来',
    coAlarm: '你买了一氧化碳报警器。密封屋子里烧火的时候，它会救你一次',
    crew: '屋里不止你一个人。潜伏期意味着你不知道谁已经带上了它',
    medbay: '有处置台和分类药柜，这会决定同一份药能救回多少',
    powerHit: '你有自己的电。从今天起，城里大多数人都没有',
    powerMiss: '没有发电。所有插电的东西从此刻起全部作废',
    fuel: '储了 {n} L 燃料，停电之后它比现金好用',
    waterHit: '储水够喝 {n} 天',
    waterMiss: '储水只够 {n} 天，而自来水刚刚停了',
    foodMiss: '食物只够 {n} 天',
    hurt: '混乱中你受了伤，生命 -{n}',
    sanity: '理智 -{n}',
    waterLost: '储水在慌乱中损失了 {n} L',
    radSick: '你吸入了沉降物：辐射病',
    floodLoot: '低处的东西全泡了：建材 -{mat}，食物 -3',
    chem: '那股味道进了屋子。你咳了一整夜，生命 -10',
    verdict75: '你准备得比这座城市里几乎所有人都好。',
    verdict50: '你有一些东西是对的，也有一些账要在后面还。',
    verdict25: '你押错了方向。接下来的每一天都会提醒你这件事。',
    verdict0: '你几乎什么都没准备对。',
    log: '{title}。{verdict}',
  },
  toast: {
    noSite: '无法选择这个站点',
    queue: '还有事情等着你处理',
    shopOpen: '商店还开着，没必要翻别人的东西',
    noAp: '行动点不足',
    needCar: '太远了，没有车去不了',
    empty: '这里已经被翻空了',
    needFuel: '这一趟要 {fuel} L 燃料，你不够',
    tired: '你累得走不出门',
    exposure: '暴露度 +{n}',
    hurt: '路上受了伤，生命 -{n}',
    droppedLoot: '跑的时候掉了战利品',
    followed: '你觉得有人跟了你一段。',
    haul: '你从{name}带回了一些东西。',
    haulOutside: '外面',
    buyFail: '买不到',
    buyPartial: '只买了 {got} L，桶满了（花了 {spent} 元）',
    buyOk: '买到 {got}，花了 {spent} 元',
    iodineFail: '买不到碘片',
    iodineOk: '买到一盒碘片（不是普通药品），花了 {spent} 元',
    restHeal: '歇了一会儿。体力、理智回了一些，生命也回了 1 点',
    rest: '歇了一会儿。体力与理智回了一些，生命不会因为躺着涨回来',
    noBuild: '无法开工',
    noWork: '无法施工',
    noSalvage: '不能这么做',
    noMaint: '现在不能做',
    noTreat: '治不了',
    treated: '处理完了',
    noIntel: '无法核实',
    noRelic: '遗物不够',
    unlocked: '已解锁',
    perkReq: '需要先点前置天赋',
    perkGot: '已获得：{name}',
    siteWip: '这个住所还在开发中，请另选一处。',
    diaryCopied: '日记已复制到剪贴板',
    recordCopied: '这一局的记录已复制',
    seedCopied: '种子已复制',
    waterRoom: '储水还能装 {room} L（上限 {cap} L）',
  },
  module: {
    none: '无',
    cistern: '储水 {cap} L（约 {days} 天）',
    filter: '雨日产 {rain} L；旱天耗水 −{save}%；滤芯损耗 ×{wear}',
    power: '光伏约 {out} kWh/日；蓄电 {cap} kWh',
    powerDiesel: '；可开柴油机补缺口',
    insulate: '失温下限 {floor}°C',
    insulateFuel: '；烧油 {fuel} L/°C',
    insulateElec: '；电热 {elec} kWh/°C',
    air: '挡污染至 {tol}；辐射屏蔽贡献 +{lvl}（停摆按 0 级计）',
    radio: '有电时提高情报与预报准确度',
    garden: '日产生鲜 {n} 份',
    medbay3: '减轻病情日损；主动休息 +1 生命',
    medbay: '减轻病情日损；提高自愈；过夜恢复略好',
    fortify: '降低袭击成功率',
    conceal: '降低每日暴露度',
  },
};

registerTree('ledger', data);
