import { registerTree } from '../t';

export const data = {
  choice: {
    skip: '什么都不做',
  },
  common: {
    close: '关闭',
    free: '免费',
    ap: '{n} AP',
    unlocked: '已解锁',
    locked: '未解锁',
    owned: '已获得',
    needReq: '需前置',
    wip: '开发中',
    condFail: '条件不足',
    yuan: '{n} 元',
    yuanUnit: '元',
    apCost: '{n} 行动点',
    parts: '{n} 零件',
    cash: '现金',
    copy: '复制',
    continue: '继续',
    settle: '结算',
    none: '无',
    today: '今天',
    dayN: '第 {n} 天',
    night: '夜',
    leftover: '还剩 {n} 天',
    threatLv: '末世等级 {n}',
    lvl: '{n} 级',
    building: '施工中',
    offline: '停摆',
    labor: '{done}/{total} 工时',
    laborSp: '{done} / {total} 工时',
    etaBuy: '第 {day} 天到货',
    etaDone: '第 {day} 天完工',
    etaDay: '第 {day} 天',
    people: '{n} 人',
    age: '{n} 岁',
    joined: '第 {n} 天加入',
    sick: '生病了',
    upkeep: '日耗 ×{n}',
    morale: '士气',
    trust: '信任',
    yes: '开',
    no: '关',
    up: '上',
    down: '下',
  },
  help: {
    title: '怎么活过这几天',
    subtitle: '规则很短。漏掉的那一条通常就是死因。',
    day: '一天',
    dayBody:
      '准备期 {prep} 天，第 {collapse} 天灾难揭晓，活到第 {final} 天判定结局。白天花行动点：采购、搜刮、施工、休息。队列里的事处理完才能结束这一天。夜里结算吃喝、供电、体温、暴露度，然后抽第二天的事件。',
    wep: '水、电、暖',
    wepBody:
      '雨雪天才接得进净水；旱天有净水就走回用，少喝一点，不是凭空产水。储水满了再接会溢出来。光伏随天气走，蓄电池有缺口才放电、有富余才回充，受发电等级上限约束。灯开着会漏光加暴露。取暖要保温 1 级才能烧燃料，2 级加发电才能用电热。施工中的保温按 0 级计。',
    heat: '屋里的温度',
    heatBody:
      '保温决定一晚漏掉多少热。人体有两条线：舒适 {comfort}°C，生存 {survival}°C。电热和烧油可以各自拉，明早室内温度是两者一起作用的结果。温控排在供电表里，它的耗电随今晚计划变，排在它下面的电器可能分不到电。预估按今天室外算明早室内，看不见明天真实气温。夜里更冷屋里会比估值低，回暖则油电少扣。低温症不能吃药，只能把屋里烧暖。',
    exposure: '暴露与袭击',
    exposureBody:
      '灯光、柴油机、同伴、搜刮都会堆热度。热度高了会有人来踩点、收税、踹门。藏好（暴露度回落到「无人注意」）后，过期的盯梢会取消。踹门时开枪、堵门都会进入袭击结算，不是开一枪对方就消失。',
    ration: '口粮不是开关',
    rationBody:
      '「充足」只是你点的档位。桶里没有东西，就不会因为档位而回血，只会挨饿。配给面板改的是需求，库存决定你实际吃到多少。',
    intel: '预报与情报',
    intelBody:
      '天气预报对着第二天的真实天气掷骰：无线电有电更准，文明崩坏后变差。情报池抽干后仍会按真伪比例复用旧消息，不会突然只剩谣言。',
  },
  collapse: {
    day: '第 {n} 天 · 灾难降临',
    count: '清点一下你手里有什么',
    score: '准备度清算',
    hits: '你做对的',
    misses: '你要还的',
    losses: '这一夜的损失',
    fromNow: '从今天起',
    fromNowBody:
      '自来水停了，电网{grid}，超市不会再上货。从现在开始，你每天要决定吃多少、喝多少、开不开灯——以及外面那些人什么时候会注意到这里还有活人。',
    gridOff: '彻底断了',
    gridRot: '开始轮流限电',
    chipThreat: '末世等级 1 · 恐慌期',
    chipRation: '配给制度生效',
    chipExposure: '暴露度开始累积',
    chipDays: '还有 {n} 天',
    ack: '开始第一天',
  },
  night: {
    title: '第 {n} 天 · 夜',
    leftover: '还剩 {n} 天',
    enter: '进入第 {n} 天',
    ellipsis: '……',
    week: '一周过去了',
    weekBody: '末世等级上升到 {n}：{desc}',
    settle: '结算',
    body: '身体',
    hp: '生命',
    sanity: '理智',
    exposure: '暴露度',
    decay: '回落 −{n}',
    outdoor: '室外 {out}°C / 室内估 {est}°C / 实际 {in}°C',
    fuel: '油 估 {est} L / 实扣 {spent} L',
    kwh: '电热 估 {est} kWh / 实用 {spent} kWh',
    died: '你没能撑过这一夜。',
    cause: '死因：{cause}。',
  },
  haul: {
    title: '{name} · 你找到了这些',
    outside: '外面',
    emptySub: '什么都没有。这里已经被翻过了。',
    capSub: '背得回去的才算你的 · 负重上限 {cap} kg',
    nightBit: ' · 夜间行动',
    dropAll: '全部丢下',
    overweight: '超重了',
    take: '带回去',
    emptyBody: '你在货架之间走了一圈，只有翻倒的塑料筐和一地碎玻璃。',
    weight: '负重',
    found: '找到 {amt} {unit} · {w} kg/单位',
    waterRoom: ' · 还能装 {room} L',
    takeAmt: '带 {n}',
    all: '全',
    danger: '这一趟的危险度是 {n}',
    nightHigher: '（夜间更高）',
    exposed: '。暴露已经结算进你的档案',
    riskHurt: '；路上可能受伤或丢掉东西',
    riskFollow: '，高危地段还有人会跟着你回家。',
    period: '。',
  },
  result: {
    title: '结果',
    checkOk: '{skill}判定 成功',
    checkBad: '{skill}判定 失败',
    d20: 'd20 {roll} + 技能 {skill} = {total} vs {dc}',
    held: '守住了',
    broken: '门被打开了',
    hp: '生命 -{n}',
    ammo: '弹药 -{n}',
    module: '{name}受损',
    died: '你没有从这一场里走出来。',
  },
  menu: {
    kicker: '民防档案 · 个人生存记录',
    title: '七日之前',
    en: 'SEVEN DAYS BEFORE',
    blurb1: '你有七天。',
    blurb2: '七天之后会发生什么，没有人能确定——而你必须在不知道答案的情况下，',
    blurb3: '把钱、时间和这栋楼里的人情，全部押出去。',
    resume: '继续 · 第 {n} 天',
    restart: '放弃当前进度，重新开始',
    start: '开始新的一局',
    confirm: '再点一次，确认结算',
    abandon: '结算当前这一局，领取遗物',
    meta: '局外成长',
    codex: '档案馆',
    record: '累计记录',
    relics: '遗物',
    runs: '游玩局数',
    best: '最长存活',
    seenEnding: '已见结局 {a}/{b}',
    seenDisaster: '已见灾难 {a}/{b}',
    seenEvent: '已见事件 {n}',
    seed: '当前存档种子',
  },
  setup: {
    kicker: '开局配置',
    title: '你是谁',
    meta: '局外成长（{n} 遗物）',
    back: '返回',
    class: '职业',
    pack: '起手物资包',
    difficulty: '难度',
    preview: '开局状况',
    perk: '专长',
    skills: '技能',
    noSkill: '没有专精',
    extra: '额外物资',
    ap: '每日行动点',
    seed: '种子（可选）',
    seedHint: '留空则随机。填入同一个种子会得到完全相同的灾难、天气与事件序列，可以用来复盘或和别人比。',
    start: '开始 · 第 1 天',
    diffDesc: {
      story: '不会死亡，产出更高。为了看故事。',
      normal: '设计意图下的平衡。',
      harsh: '产出更低，袭击更凶，遗物 ×1.5。',
    },
  },
  site: {
    kicker: '第 1 天 · 上午',
    cash: '现金',
    title: '你要在哪里熬过去',
    blurb:
      '这是整局最重要的一个决定。站点不只是数值差异——它决定了你能建什么、建到几级，也决定了七天之后哪些事会发生在你身上。地下车库不会有人从窗户翻进来，但它会内涝。',
    caps: '{name} · 模块等级上限',
    capHint: '{name}：上限 {n} 级',
    included: '自带',
    buildable: '可建',
    limited: '受限',
    stats: '搜刮 ×{loot} · 收留上限 {cap} 人 · 储水 ×{water}',
    here: '就这里 · {cost}',
    look: '再看看',
  },
  summary: {
    win: '结局',
    death: '死亡',
    thisRun: '这一局',
    relics: '遗物结算',
    gained: '本局获得',
    unlocks: '新解锁',
    lastLog: '日记的最后几行',
    logLine: '第 {n} 天　{text}',
    claim: '领取 {n} 遗物，回到菜单',
    copy: '复制这一局的完整记录',
    exportTitle: '《七日之前》 · {title}（{sub}）',
    exportMeta: '{cls} · {site} · {disaster}',
    exportDays: '存活 {days} 天 · 末世等级 {threat} · 种子 {seed}',
    scavenge: '外出次数',
    raids: '挡住的袭击',
    saved: '收留的人',
    humanity: '人性',
  },
  meta: {
    title: '局外成长',
    subtitle: '遗物 {n} · 每一局的存活天数与结局都会变成这里的进度',
    perks: '天赋树（{a}/{b}）',
    unlocks: '解锁',
    relics: '遗物',
    class: '职业',
    site: '站点',
    pack: '起手物资包',
    unlockHint: '部分内容也可以通过达成特定结局直接解锁——那样不花遗物。',
    codex: '档案馆',
    codexSub: '你见过的东西会留在这里。见过越多，下一局你知道得越多。',
    tabEnding: '结局 {a}/{b}',
    tabDisaster: '灾难 {a}/{b}',
    tabEvent: '事件 {a}/{b}',
    tabClass: '职业',
    unseen: '？？？',
    undiscovered: '未发现',
    winHint: '还有一条活路你没走到。',
    deathHint: '还有一种死法你没遇到。',
    unknownDisaster: '未知灾难',
    keySupplies: '关键物资',
    clues: '线索关键词',
    disasterHint: '经历过一次之后，这里会列出它的线索关键词与关键物资。',
    noEvents: '还没有记录任何事件。',
    unrecorded: '未记录',
    variants: '{a}/{b} 种情形',
    intensity: '强度 {n} · 冷却 {cd} 天',
    once: ' · 每局一次',
  },
  game: {
    countdown: '倒计时',
    dayPrefix: '第',
    daySuffix: '天',
    status: '状态',
    preDisaster: '灾难尚未到来',
    weather: '天候',
    outdoor: '室外 {out}°C / 室内 {in}°C',
    env: '环境',
    rad: '辐射 {n} / 可挡 {tol}',
    filterOff: '过滤停摆，按 0 级计',
    iodine: '碘片保护中',
    battery: '蓄电 {stored}/{cap}',
    air: '空气 {n}',
    contagion: '疫情 {n}',
    law: '秩序 {n}',
    disaster: '灾难',
    ap: '行动点',
    shelter: '避难所',
    power: '供电',
    shop: '采购',
    out: '外出',
    intel: '情报',
    log: '日记',
    tapOn: '自来水与超市仍在运转',
    queueHint: '得先把眼前的事处理完，才能安排今天要干什么。',
    body: '身体状况',
    hp: '生命',
    stamina: '体力',
    sanity: '理智',
    humanity: '人性',
    reputation: '名声',
    treat: '需要处理',
    worsenNow: '已拖 {age} 天，随时可能恶化为{name}。',
    worsenLater: '已拖 {age} 天，再拖约 {left} 天可能恶化。',
    treatTitle: '消耗 {n} 组药品',
    treatMedbay: ' + {n} 级医疗站',
    treatBtn: '用药 {n}',
    treatMed: ' · 医{n}',
    treatNote: ' 用药只解除状态，不回生命。',
    medbay: '医疗站减轻病情损耗',
    medbay3: '；三级时主动休息能回 1 点生命',
    medbaySleep: '；过夜恢复略好',
    treatRule: '。治疗只解除状态，不额外回血。',
    prepTitle: '今日安排',
    prepBody: '自来水还在供，超市还开着门。配给制度从灾难降临的那天开始生效。',
    heads: '家里现在有几个人',
    perWater: '每人每日需水',
    perWaterVal: '约 3 L',
    rationTitle: '计划',
    food: '口粮',
    foodNeed: '需 {n} 份',
    ration: { full: '充足', normal: '标准', half: '减半', none: '断粮' },
    water: '用水',
    waterNeed: '需 {n} L',
    waterUse: { full: '充足', normal: '标准', limited: '限量' },
    heat: '取暖',
    indoor: '室内 {n}°C',
    heatNow: '现在 {n}°C',
    heatEst: '预估明日室内温度 {n}°C',
    heatOutdoor: '室外 {n}°C',
    heatSurvival: '生存',
    heatComfort: '舒适',
    heatElecSlider: '电',
    heatFuelSlider: '油',
    powerLabel: '供电',
    powerBtn: '供电优先级',
    solarEst: '预估发电 {n} kWh',
    powerOff: '电力不足，已停摆：{list}',
    actions: '今天做什么',
    apLeft: '剩 {n} 行动点',
    buyTitle: '出门采购',
    buyDesc: '超市、五金店、药店、加油站、旧货市场。物价每天都在涨，限购是真的，货架会空。',
    scavTitle: '外出搜刮',
    scavDesc: '外面还剩下的东西越来越少。危险会变成暴露，夜里更高。燃料或体力不够就出不去。',
    buildTitle: '避难所工程',
    buildDesc: '自己动手、雇人、或者买成品。施工中的模块处于劣化状态——挑对时机很重要。',
    intelPrep: '分析情报',
    intelPrepDesc: '每天三条消息，真假混杂。你要靠它们猜出七天后会来的是什么。',
    intelLive: '收听无线电',
    intelLiveDesc: '外面还在广播什么，谁还活着，往哪走。',
    rest: '休息',
    restHeal: '恢复体力和一点理智，并回 1 点生命。',
    restPlain: '恢复体力和一点理智。不回生命。有时候什么都不做是正确的选择。',
    noTime: '今天的时间用完了。结束这一天，看看夜里会发生什么。',
    supplies: '物资',
    batteryLabel: '蓄电',
    daysWater: '水 {n} 天',
    daysFood: '粮 {n} 天',
    cistern: '储水上限 {n} L',
    spoil: ' · 生鲜每天会腐败一部分，先吃它',
    manage: '管理',
    moduleTip: '{name} {lvl} 级',
    buildingTip: '（施工中，当前失效）',
    offlineTip: '（停摆）',
    buildingShort: '施工',
    queue: '施工队列',
    filterWarn: '滤芯还能用 {n} 天。用尽后净水与空气过滤会直接失效。',
    exposure: '暴露度',
    tonight: '今夜将累积',
    menu: '菜单',
    rules: '规则',
    queueWait: '还有事情等着你处理。',
    apUnused: '还剩 {n} 个行动点没用。',
    noAp: '今天没有时间了。',
    endDay: '结束这一天',
  },
  event: {
    more: '还有 {n} 件事',
    scramble: '你已经很久没睡好了。你不完全确定刚才读到的每一个细节都真的发生过。',
    intensity: '强度 {bars}',
  },
  shelter: {
    title: '避难所 · {name}',
    subtitle: '施工中的模块处于劣化状态。什么时候动工，本身就是一个决定。',
    current: '当前：{fx}',
    next: ' → 下一级：{fx}',
    target: '{path} · 目标 {n} 级',
    work: '投入 1 行动点施工',
    cancel: '停工（回收一半材料）',
    upTo: '升到 {n} 级 · {desc}',
    failRisk: '技能不足，每次施工有 {pct}% 概率做坏',
    power: '每日耗电 {n} kWh',
    atCap: '已经到达这个站点允许的上限。',
    maint: '维护',
    maintHint: '保养滤芯/机油也会推进某些还没结束的事。',
    remain: '剩 {n} 天',
    maintCost: '{n} 零件 · 1 行动点',
    salvage: '拆解回收',
    salvageHint: '现在买不到建材了。你只能从已经存在的东西上取——每一次都会制造声音，有些还会制造敌人。',
    exposure: '暴露 +{n}',
    humanity: '人性 {n}',
    salvageRange: '建材 {a}-{b} · 零件 {c}-{d}',
  },
  map: {
    shop: '采购',
    out: '外出',
    price: '物价指数 {n}',
    limited: ' · 已开始限购',
    scavSub: '越远的地方存量越多，也越难回来。危险会变成暴露，高危可能被人盯上。',
    when: '出行时段',
    day: '白天',
    nightOwl: '夜间（产出 +60%，危险减轻，仍会增加暴露）',
    night: '夜间（产出 +40%，危险 ×1.8，暴露上升）',
    near: '近',
    mid: '中',
    far: '远',
    danger: '危险 {n}',
    needCar: '需要车',
    empty: '已空',
    stock: '存量 {n}%',
    blocked: '设卡',
    visited: '今日已去过',
    shopAgain: '再看看货架',
    shopGo: '去采购（1 AP）',
    scavEmpty: '已经空了',
    scavGo: '搜刮（1 AP）',
    scavNight: '搜刮（1 AP · 夜间）',
  },
  intel: {
    board: '情报板',
    radio: '无线电与局势',
    boardSub: '真假混杂。你要在第七天之前赌对一个方向。',
    radioSub: '灾难已经揭晓，现在你要判断的是外面还剩下什么。',
    infer: '方向推断',
    inferHint: '指向某个方向的情报越多，它越可能是真的——但制造噪音也很容易。核实过的情报会给出确认结果，那才是硬信息。',
    count: '{n} 条',
    true: '确认真 {n}',
    false: '确认假 {n}',
    keys: '关键物资：{list}',
    stream: '情报流',
    empty: '还没有收到任何东西。',
    today: ' · 今天',
    verifiedTrue: '核实：真',
    verifiedFalse: '核实：误导',
    verify: '核实（1 AP）',
    current: '当前灾难 · {name}',
    keySupplies: '关键物资',
    factions: '活跃势力',
    forecast: '天气预报',
    accuracy: '准确度 {n}%',
    radioOn: '无线电有电，预报更可靠。提前一天知道寒潮，就能提前一天囤燃料。',
    radioOff: '电台因缺电停摆，预报不准。把它排到供电表前面，或关掉别的负荷。',
    noRadio: '没有无线电，你只能靠看天。装一台会让预报准得多。',
    world: '局势指标',
    law: '秩序度',
    scarcity: '物资稀缺度',
    neighborhood: '社区关系',
    air: '空气污染',
    rad: '辐射',
    contagion: '疫病流行度',
  },
  crew: {
    title: '这里的人',
    subtitle: '{n} / {cap} 人 · 每个人都是一份劳力，也是一份口粮',
    empty: '只有你一个人。这既是最安全的，也是最难熬的。',
    secretSoon: '他还有些话没说。信任够高的时候，你会知道。',
  },
  log: {
    title: '记忆日记',
    subtitle: '这一局发生过的事，按天记录',
    copy: '复制全文',
    empty: '还没有什么值得写下来的。',
    exportTitle: '《七日之前》记忆日记',
    exportSeed: '种子 {n}',
    line: '第 {n} 天　{text}',
    prep: ' · D-{n}',
  },
  shop: {
    price: '物价指数 {n} · 货架 {stock}%',
    limited: ' · 已限购',
    empty: '这里不卖东西。',
    iodine: '碘片',
    notMeds: '不是普通药品',
    box: '{n} 元 / 盒',
    iodineHint: '限购 {limit} 盒。买下即生效，核沉降时挡甲状腺剂量。柜台剩 {left} 盒。',
    bought: '已买过了',
    buyBox: '买 1 盒',
    unit: '{price} 元 / {unit}',
    remain: '今日剩余 {limit} {unit} · 现有 {have}',
    waterRoom: ' · 还能装 {room} L（上限 {cap} L）',
    waterFull: '储水已满',
    dayFull: '今日已买满',
    shelfEmpty: '货架空了',
    cash: '现金',
    cashAmt: '{n} 元',
  },
  power: {
    title: '供电优先级',
    subtitle: '关掉或往后排就是省电。光伏随天气走，柴油机只补缺口。',
    gridOk: '市电充足：今晚不会因缺电停摆（自己拆线路除外）。',
    efficiency: '发电效率',
    efficiencyPct: '{n}%',
    factorTip: '光伏 ×{n}',
    factorNuclear: '核沉降',
    factorVolcanic: '火山灰幕',
    factorFlood: '洪涝',
    factorChem: '化学雾',
    kwh: '{n} kWh',
    grid: '市电 +{n} kWh',
    batt: '蓄电 {stored}/{cap} kWh',
    discharge: ' · 今晚放电 {n}',
    charge: ' · 今晚可充 {n}',
    dieselOn: '柴油机补 {gen} kWh / 烧 {fuel} L',
    dieselIdle: '柴油机待命：光伏够用就不转',
    tonight: '今晚可用 ',
    demand: ' / 想开着的负荷 ',
    table: '负荷表（越靠上越优先保电）',
    on: '今晚有电',
    off: '今晚会停',
    closed: '已关掉',
    lights: '开着漏光加暴露；关掉理智夜间 −6',
    fridge: '关掉则生鲜腐败加快',
    heater: '温控：今晚计划用电 {kwh} kWh，室内目标 {n}°C',
    air: '停摆时辐射屏蔽按 0 级计',
    radio: '没电则情报和预报不准',
    nuclear: '核沉降',
    disasterGeneric: '灾难',
  },
};

registerTree('ui', data);
